# Generated by Django 4.2.26 on 2026-06-03 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('privy_user_id', models.CharField(blank=True, max_length=160, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('wallet_address', models.CharField(blank=True, max_length=64, null=True)),
                ('smart_wallet_address', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=160)),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('occupation', models.CharField(blank=True, default='', max_length=160)),
                ('gender', models.CharField(blank=True, default='', max_length=40)),
                ('country', models.CharField(blank=True, default='Korea', max_length=80)),
                ('residence', models.CharField(blank=True, default='', max_length=120)),
                ('display_name', models.CharField(blank=True, default='', max_length=160)),
                ('public_slug', models.CharField(blank=True, default='', max_length=160)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('payout_address', models.CharField(blank=True, max_length=64, null=True)),
                ('has_profile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'app_users',
                'indexes': [models.Index(fields=['email'], name='app_users_email_idx'), models.Index(fields=['wallet_address'], name='app_users_wallet_idx'), models.Index(fields=['public_slug'], name='app_users_slug_idx')],
            },
        ),
        migrations.CreateModel(
            name='AppEducation',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('education', models.CharField(blank=True, db_column='school', default='', max_length=240)),
                ('status', models.CharField(blank=True, default='graduated', max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='users.appuser')),
            ],
            options={
                'db_table': 'app_educations',
                'indexes': [models.Index(fields=['user', 'sort_order'], name='app_edu_user_sort_idx')],
            },
        ),
        migrations.CreateModel(
            name='AppCareer',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('career', models.CharField(blank=True, db_column='title', default='', max_length=240)),
                ('start_date', models.CharField(blank=True, default='', max_length=16)),
                ('end_date', models.CharField(blank=True, default='', max_length=16)),
                ('status', models.CharField(blank=True, default='employed', max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='users.appuser')),
            ],
            options={
                'db_table': 'app_careers',
                'indexes': [models.Index(fields=['user', 'sort_order'], name='app_career_user_sort_idx')],
            },
        ),
    ]
