# Generated by Django 4.2.26 on 2026-06-03 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDataField',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=24)),
                ('label', models.CharField(max_length=120)),
                ('value_preview', models.TextField(blank=True, default='')),
                ('access_mode', models.CharField(default='free', max_length=16)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='IP', max_length=8)),
                ('requires_verification', models.BooleanField(default=False)),
                ('verification_status', models.CharField(default='not_required', max_length=24)),
                ('cdr_state', models.CharField(default='off', max_length=16)),
                ('seller_address', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_fields', to='users.appuser')),
            ],
            options={
                'db_table': 'app_data_fields',
            },
        ),
        migrations.CreateModel(
            name='AppExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField()),
                ('format', models.CharField(max_length=16)),
                ('successful_field_ids', models.JSONField(default=list)),
                ('failed_field_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'app_export_logs',
            },
        ),
        migrations.CreateModel(
            name='AppOrder',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('buyer_wallet', models.CharField(max_length=64)),
                ('prompt', models.TextField(blank=True, default='')),
                ('filters', models.JSONField(default=dict)),
                ('selected_profile_ids', models.JSONField(default=list)),
                ('selected_match_refs', models.JSONField(default=list)),
                ('selected_field_ids', models.JSONField(default=list)),
                ('subtotal_cents', models.PositiveIntegerField(default=0)),
                ('service_fee_cents', models.PositiveIntegerField(default=0)),
                ('total_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='IP', max_length=8)),
                ('batch_size', models.PositiveIntegerField(default=100)),
                ('platform_fee_bps', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='pending_payment', max_length=32)),
                ('payment_tx_hash', models.CharField(blank=True, max_length=96, null=True)),
                ('license_token_ids', models.JSONField(default=list)),
                ('license_token_grants', models.JSONField(default=list)),
                ('purchase_contract', models.CharField(blank=True, default='', max_length=64)),
                ('access_proof', models.CharField(blank=True, default='', max_length=96)),
                ('sheet_params', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'app_orders',
            },
        ),
        migrations.CreateModel(
            name='AppSearchDocument',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='search_document', serialize=False, to='users.appuser')),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('gender', models.CharField(blank=True, default='', max_length=40)),
                ('country', models.CharField(blank=True, default='Korea', max_length=80)),
                ('residence', models.CharField(blank=True, default='', max_length=120)),
                ('occupation', models.CharField(blank=True, default='', max_length=160)),
                ('tags', models.JSONField(default=list)),
                ('searchable_text', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'app_search_documents',
                'indexes': [models.Index(fields=['age'], name='app_search_age_idx'), models.Index(fields=['country', 'residence'], name='app_search_country_idx')],
            },
        ),
        migrations.CreateModel(
            name='AppQuote',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('buyer_wallet', models.CharField(blank=True, default='', max_length=64)),
                ('prompt', models.TextField(blank=True, default='')),
                ('filters', models.JSONField(default=dict)),
                ('recommended_fields', models.JSONField(default=list)),
                ('wanted_fields', models.JSONField(default=list)),
                ('profile_ids', models.JSONField(default=list)),
                ('matches', models.JSONField(default=list)),
                ('extensions', models.JSONField(default=list)),
                ('matched_profile_count', models.PositiveIntegerField(default=0)),
                ('paid_field_count', models.PositiveIntegerField(default=0)),
                ('free_field_count', models.PositiveIntegerField(default=0)),
                ('subtotal_cents', models.PositiveIntegerField(default=0)),
                ('service_fee_cents', models.PositiveIntegerField(default=0)),
                ('total_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='IP', max_length=8)),
                ('batch_size', models.PositiveIntegerField(default=100)),
                ('capped', models.BooleanField(default=False)),
                ('max_paid_fields', models.PositiveIntegerField(default=800)),
                ('sheet_params', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'app_quotes',
                'indexes': [models.Index(fields=['buyer_wallet', '-created_at'], name='app_quote_buyer_idx')],
            },
        ),
        migrations.CreateModel(
            name='AppOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_ref', models.CharField(blank=True, default='', max_length=80)),
                ('kind', models.CharField(max_length=24)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('seller_address', models.CharField(max_length=64)),
                ('cdr_vault_uuid', models.CharField(blank=True, max_length=120, null=True)),
                ('access_aux_data', models.TextField(blank=True, null=True)),
                ('license_token_id', models.CharField(blank=True, max_length=80, null=True)),
                ('license_mint_tx_hash', models.CharField(blank=True, max_length=96, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='data.appdatafield')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='data.apporder')),
                ('seller_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_items', to='users.appuser')),
            ],
            options={
                'db_table': 'app_order_items',
            },
        ),
        migrations.AddField(
            model_name='apporder',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.appquote'),
        ),
        migrations.CreateModel(
            name='AppExportLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
                ('error', models.TextField(blank=True, null=True)),
                ('export_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='data.appexportlog')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.apporderitem')),
            ],
            options={
                'db_table': 'app_export_log_items',
            },
        ),
        migrations.AddField(
            model_name='appexportlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_logs', to='data.apporder'),
        ),
        migrations.CreateModel(
            name='AppVerification',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=16)),
                ('target', models.CharField(max_length=240)),
                ('provider', models.CharField(max_length=40)),
                ('code_hash', models.CharField(blank=True, default='', max_length=96)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.appdatafield')),
            ],
            options={
                'db_table': 'app_verifications',
                'indexes': [models.Index(fields=['field', '-created_at'], name='app_verify_field_idx'), models.Index(fields=['target', '-created_at'], name='app_verify_target_idx')],
            },
        ),
        migrations.CreateModel(
            name='AppOrderSellerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_address', models.CharField(max_length=64)),
                ('field_ids', models.JSONField(default=list)),
                ('gross_cents', models.PositiveIntegerField(default=0)),
                ('seller_cents', models.PositiveIntegerField(default=0)),
                ('service_fee_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_payouts', to='data.apporder')),
            ],
            options={
                'db_table': 'app_order_seller_payouts',
                'indexes': [models.Index(fields=['seller_address'], name='app_payout_seller_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='appordersellerpayout',
            constraint=models.UniqueConstraint(fields=('order', 'seller_address'), name='app_order_payout_unique'),
        ),
        migrations.AddIndex(
            model_name='apporderitem',
            index=models.Index(fields=['order'], name='app_item_order_idx'),
        ),
        migrations.AddIndex(
            model_name='apporderitem',
            index=models.Index(fields=['field'], name='app_item_field_idx'),
        ),
        migrations.AddIndex(
            model_name='apporderitem',
            index=models.Index(fields=['seller_address'], name='app_item_seller_idx'),
        ),
        migrations.AddConstraint(
            model_name='apporderitem',
            constraint=models.UniqueConstraint(fields=('order', 'field'), name='app_order_item_unique'),
        ),
        migrations.AddIndex(
            model_name='apporder',
            index=models.Index(fields=['buyer_wallet', '-created_at'], name='app_order_buyer_idx'),
        ),
        migrations.AddIndex(
            model_name='apporder',
            index=models.Index(fields=['status', '-created_at'], name='app_order_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='appexportlogitem',
            constraint=models.UniqueConstraint(fields=('export_log', 'order_item'), name='app_export_item_unique'),
        ),
        migrations.AddIndex(
            model_name='appexportlog',
            index=models.Index(fields=['order', '-created_at'], name='app_export_order_idx'),
        ),
        migrations.AddIndex(
            model_name='appdatafield',
            index=models.Index(fields=['user', 'kind'], name='app_field_user_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='appdatafield',
            index=models.Index(fields=['kind', 'price_cents'], name='app_field_kind_price_idx'),
        ),
        migrations.AddIndex(
            model_name='appdatafield',
            index=models.Index(fields=['seller_address'], name='app_field_seller_idx'),
        ),
        migrations.AddConstraint(
            model_name='appdatafield',
            constraint=models.UniqueConstraint(fields=('user', 'kind'), name='app_field_user_kind_unique'),
        ),
    ]
