# Generated by Django 4.2.26 on 2026-06-03 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCdrVault',
            fields=[
                ('id', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('network', models.CharField(default='aeneid', max_length=40)),
                ('cdr_vault_uuid', models.CharField(max_length=120)),
                ('slot_id', models.CharField(blank=True, max_length=96, null=True)),
                ('owner_address', models.CharField(blank=True, max_length=64, null=True)),
                ('write_condition_address', models.CharField(blank=True, max_length=64, null=True)),
                ('read_condition_address', models.CharField(blank=True, max_length=64, null=True)),
                ('write_condition_data', models.TextField(blank=True, default='0x')),
                ('read_condition_data', models.TextField(blank=True, null=True)),
                ('allocate_tx_hash', models.CharField(blank=True, max_length=96, null=True)),
                ('deploy_tx_hash', models.CharField(blank=True, max_length=96, null=True)),
                ('cdr_license_ip_id', models.CharField(blank=True, max_length=64, null=True)),
                ('cdr_license_terms_id', models.CharField(blank=True, max_length=80, null=True)),
                ('platform_wallet', models.CharField(blank=True, max_length=64, null=True)),
                ('ipa_recipient', models.CharField(blank=True, max_length=64, null=True)),
                ('ipa_nft_contract', models.CharField(blank=True, max_length=64, null=True)),
                ('ipa_token_id', models.CharField(blank=True, max_length=80, null=True)),
                ('ip_registration_tx_hash', models.CharField(blank=True, max_length=96, null=True)),
                ('ipa_transfer_tx_hash', models.CharField(blank=True, max_length=96, null=True)),
                ('license_config_tx_hash', models.CharField(blank=True, max_length=96, null=True)),
                ('license_attach_tx_hash', models.CharField(blank=True, max_length=96, null=True)),
                ('status', models.CharField(default='active', max_length=24)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cdr_vault', to='data.appdatafield')),
            ],
            options={
                'db_table': 'app_cdr_vaults',
            },
        ),
        migrations.CreateModel(
            name='AppOnchainSale',
            fields=[
                ('id', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('buyer_wallet', models.CharField(max_length=64)),
                ('seller_address', models.CharField(max_length=64)),
                ('kind', models.CharField(blank=True, default='', max_length=24)),
                ('label', models.CharField(blank=True, default='Paid data', max_length=120)),
                ('cdr_license_ip_id', models.CharField(blank=True, max_length=64, null=True)),
                ('gross_cents', models.PositiveIntegerField(default=0)),
                ('seller_cents', models.PositiveIntegerField(default=0)),
                ('service_fee_cents', models.PositiveIntegerField(default=0)),
                ('payment_tx_hash', models.CharField(max_length=96)),
                ('block_number', models.CharField(blank=True, max_length=80, null=True)),
                ('log_index', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(default='onchain', max_length=24)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.appdatafield')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.apporder')),
            ],
            options={
                'db_table': 'app_onchain_sales',
                'indexes': [models.Index(fields=['seller_address', '-created_at'], name='app_sale_seller_idx'), models.Index(fields=['buyer_wallet', '-created_at'], name='app_sale_buyer_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='apponchainsale',
            constraint=models.UniqueConstraint(fields=('payment_tx_hash', 'field'), name='app_onchain_sale_unique'),
        ),
        migrations.AddIndex(
            model_name='appcdrvault',
            index=models.Index(fields=['field'], name='app_cdr_field_idx'),
        ),
        migrations.AddIndex(
            model_name='appcdrvault',
            index=models.Index(fields=['network', 'cdr_vault_uuid'], name='app_cdr_network_idx'),
        ),
        migrations.AddIndex(
            model_name='appcdrvault',
            index=models.Index(fields=['status'], name='app_cdr_status_idx'),
        ),
    ]
